# Generated by Django 4.1.4 on 2023-07-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="Name",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="student",
            name="Roll",
            field=models.IntegerField(),
        ),
    ]
